
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: ishtar
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache

